% Generated by stexcasp.
% Root: http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=EU&s=EU
% Edges point from a concept to the concepts used by its definition.

#pred not_implemented(Predicate, Arity, X) :: '@(Predicate)/@(Arity) is not implemented for @(X)'.
#pred belief(X) :: '@(X): http://mathhub.info?a=smglom/epistemology&p=mod&m=belief&s=belief'.
#pred court(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Procedural-Law&p=mod&m=court&s=court'.
#pred economic_union(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=economic-union&s=economic%20union'.
#pred eu(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=EU&s=EU'.
#pred executive(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=executive&s=executive'.
#pred federal(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=federal'.
#pred government(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=government&s=government'.
#pred identity(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Personal-Data-Protection-Law&p=mod/personal-data&m=identity&s=identity'.
#pred judiciary(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=judiciary&s=judiciary'.
#pred law(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Philosophy&p=mod&m=law&s=law'.
#pred legal(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Philosophy&p=mod&m=law&s=legal'.
#pred legislature(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=legislature&s=legislature'.
#pred member(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=member'.
#pred member_state(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=member-state&s=member%20state'.
#pred organization(X) :: '@(X): http://mathhub.info?a=smglom/orga&p=mod&m=organization&s=organization'.
#pred person(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-General-Terms&p=mod&m=person&s=person'.
#pred policy(X) :: '@(X): http://mathhub.info?a=smglom/search&p=mod&m=policy&s=policy'.
#pred political_union(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=political%20union'.
#pred polity(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=polity&s=polity'.
#pred set(X) :: '@(X): http://mathhub.info?a=smglom/sets&p=mod&m=set&s=set'.
#pred state(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=state&s=state'.
#pred supranational_union(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=supranational-union&s=supranational%20union'.
#pred territory(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=territory&s=territory'.
#pred trade_bloc(X) :: '@(X): http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=trade-bloc&s=trade%20bloc'.

% eu/1 <- http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=EU&s=EU
eu(X) :-
    economic_union(X),
    member_state(X),
    political_union(X),
    supranational_union(X),
    not_implemented(eu, 1, X).

% belief/1 <- http://mathhub.info?a=smglom/epistemology&p=mod&m=belief&s=belief
belief(X) :- not_implemented(belief, 1, X).

% court/1 <- http://mathhub.info?a=JLogic/smglol/Procedural-Law&p=mod&m=court&s=court
court(X) :- not_implemented(court, 1, X).

% economic_union/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=economic-union&s=economic%20union
economic_union(X) :-
    member(X),
    policy(X),
    state(X),
    trade_bloc(X),
    not_implemented(economic_union, 1, X).

% executive/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=executive&s=executive
executive(X) :- not_implemented(executive, 1, X).

% federal/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=federal
federal(X) :- not_implemented(federal, 1, X).

% government/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=government&s=government
government(X) :-
    executive(X),
    judiciary(X),
    legislature(X),
    not_implemented(government, 1, X).

% identity/1 <- http://mathhub.info?a=JLogic/smglol/Personal-Data-Protection-Law&p=mod/personal-data&m=identity&s=identity
identity(X) :-
    belief(X),
    person(X),
    set(X),
    not_implemented(identity, 1, X).

% judiciary/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=judiciary&s=judiciary
judiciary(X) :-
    court(X),
    law(X),
    legal(X),
    not_implemented(judiciary, 1, X).

% law/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Philosophy&p=mod&m=law&s=law
law(X) :- not_implemented(law, 1, X).

% legal/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Philosophy&p=mod&m=law&s=legal
legal(X) :- not_implemented(legal, 1, X).

% legislature/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=legislature&s=legislature
legislature(X) :- not_implemented(legislature, 1, X).

% member/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=member
member(X) :-
    federal(X),
    government(X),
    polity(X),
    not_implemented(member, 1, X).

% member_state/1 <- http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=member-state&s=member%20state
member_state(X) :- not_implemented(member_state, 1, X).

% organization/1 <- http://mathhub.info?a=smglom/orga&p=mod&m=organization&s=organization
organization(X) :- not_implemented(organization, 1, X).

% person/1 <- http://mathhub.info?a=JLogic/smglol/Legal-General-Terms&p=mod&m=person&s=person
person(X) :- not_implemented(person, 1, X).

% policy/1 <- http://mathhub.info?a=smglom/search&p=mod&m=policy&s=policy
policy(X) :- not_implemented(policy, 1, X).

% political_union/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=political%20union
political_union(X) :-
    federal(X),
    government(X),
    polity(X),
    not_implemented(political_union, 1, X).

% polity/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=polity&s=polity
polity(X) :-
    identity(X),
    not_implemented(polity, 1, X).

% set/1 <- http://mathhub.info?a=smglom/sets&p=mod&m=set&s=set
set(X) :- not_implemented(set, 1, X).

% state/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=state&s=state
state(X) :-
    government(X),
    polity(X),
    territory(X),
    not_implemented(state, 1, X).

% supranational_union/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=supranational-union&s=supranational%20union
supranational_union(X) :-
    organization(X),
    political_union(X),
    state(X),
    not_implemented(supranational_union, 1, X).

% territory/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=territory&s=territory
territory(X) :- not_implemented(territory, 1, X).

% trade_bloc/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=trade-bloc&s=trade%20bloc
trade_bloc(X) :-
    organization(X),
    state(X),
    not_implemented(trade_bloc, 1, X).

% Every generated predicate starts as an open proof obligation.
not_implemented(belief, 1, _).
not_implemented(court, 1, _).
not_implemented(economic_union, 1, _).
not_implemented(eu, 1, _).
not_implemented(executive, 1, _).
not_implemented(federal, 1, _).
not_implemented(government, 1, _).
not_implemented(identity, 1, _).
not_implemented(judiciary, 1, _).
not_implemented(law, 1, _).
not_implemented(legal, 1, _).
not_implemented(legislature, 1, _).
not_implemented(member, 1, _).
not_implemented(member_state, 1, _).
not_implemented(organization, 1, _).
not_implemented(person, 1, _).
not_implemented(policy, 1, _).
not_implemented(political_union, 1, _).
not_implemented(polity, 1, _).
not_implemented(set, 1, _).
not_implemented(state, 1, _).
not_implemented(supranational_union, 1, _).
not_implemented(territory, 1, _).
not_implemented(trade_bloc, 1, _).

?- eu(X), not_implemented(Node, Arity, X).
