% Generated by stexcasp.
% Root: http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=EU&s=EU
% Edges point from a concept to the concepts used by its definition.

#pred not_implemented(Predicate, Arity, X) :: '@(Predicate)/@(Arity) is not implemented for @(X)'.
#pred court(X) :: 'A @(X) is a constitutionally guaranteed, state-established institution and the judicial branch entrusted with the authoritative exercise of judicial power. @(X) are primarily organized in judicial panels. @(X) serve to enforce law and order in relations between citizens, between citizens and the state, and between states. This enforcement is primarily achieved –— with the exception of criminal proceedings –— through judicial or extrajudicial dispute resolution, i.e., trhough litigation and arbitration.'.
#pred eu(X) :: 'The @(X) (@(X)) is a unique supranational, political and economic union of 27 member states that are primarily lovated in Europe. The member states have agreed to cooperate and share sovereignty in key areas through a system of supranational governance.'.
#pred government(X) :: 'A @(X) is the system or group of people governing an organized community, generally a state, it normally consists of legislature, executive, and judiciary.'.
#pred identity(X) :: 'An @(X) Identität refers to certain facts or properties, i.e., the set of qualities, beliefs, personality traits, appearance, or expressions who or what characterizes — we say identify a person. Herethrough, this Person is assigned a property by which this Person distinguishes itself from other persons Person.'.
#pred judiciary(X) :: 'The @(X) (also known as the @(X), @(X), @(X), @(X), and @(X) or @(X)) is the system of courts that adjudicates legal disputes/disagreements and interprets, defends, and applies the law in legal cases.'.
#pred law(X) :: 'The law is a set of rules that are created and are enforceable by social or governmental institutions to regulate behavior. The law is usually given as a set of @(X): documents that codify these rules. If a subject matter relates to the system of law governing a society, it is called a legal subject matter.'.
#pred legal(X) :: 'The law is a set of rules that are created and are enforceable by social or governmental institutions to regulate behavior. The law is usually given as a set of laws: documents that codify these rules. If a subject matter relates to the system of law governing a society, it is called a @(X) subject matter.'.
#pred member_state(X) :: 'A @(X) is a sovereign country that has voluntarily joined the EU and agreed to abide by its treaties, laws, and institutions.'.
#pred person(X) :: '@(X) sind Rechtssubjekte, die ihre Rechtsfähigkeit von der jeweiligen Rechtsordnung erhalten haben und am Rechtsverkehr teilnehmen können. Jede @(X) besitzt ihre eigenen Rechte und Pflichte.'.
#pred polity(X) :: 'A @(X) (@(X)) is a group of people with a collective identity, who are organized by some form of political institutionalized social relations, and have a capacity to mobilize resources.'.
#pred state(X) :: 'A @(X) is a political entity that regulates society and the population within a definite territory. Government is considered to form the fundamental apparatus of contemporary states.'.
#pred supranational_union(X) :: 'A @(X) is a type of international organization and political union that is empowered to directly exercise some of the powers and functions otherwise reserved to sovereign states.'.
#pred territory(X) :: 'A @(X) is an area of land, sea, or space, belonging or connected to a particular state, person, or animal.'.

% eu/1 <- http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=EU&s=EU
eu(X) :-
    economic_union(X),
    member_state(X),
    political_union(X),
    supranational_union(X),
    not_implemented(eu, 1, X).

% belief/1 <- http://mathhub.info?a=smglom/epistemology&p=mod&m=belief&s=belief
belief(X) :- not_implemented(belief, 1, X).

% court/1 <- http://mathhub.info?a=JLogic/smglol/Procedural-Law&p=mod&m=court&s=court
court(X) :- not_implemented(court, 1, X).

% economic_union/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=economic-union&s=economic%20union
economic_union(X) :-
    member(X),
    policy(X),
    state(X),
    trade_bloc(X),
    not_implemented(economic_union, 1, X).

% executive/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=executive&s=executive
executive(X) :- not_implemented(executive, 1, X).

% federal/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=federal
federal(X) :- not_implemented(federal, 1, X).

% government/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=government&s=government
government(X) :-
    executive(X),
    judiciary(X),
    legislature(X),
    not_implemented(government, 1, X).

% identity/1 <- http://mathhub.info?a=JLogic/smglol/Personal-Data-Protection-Law&p=mod/personal-data&m=identity&s=identity
identity(X) :-
    belief(X),
    person(X),
    set(X),
    not_implemented(identity, 1, X).

% judiciary/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=judiciary&s=judiciary
judiciary(X) :-
    court(X),
    law(X),
    legal(X),
    not_implemented(judiciary, 1, X).

% law/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Philosophy&p=mod&m=law&s=law
law(X) :- not_implemented(law, 1, X).

% legal/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Philosophy&p=mod&m=law&s=legal
legal(X) :- not_implemented(legal, 1, X).

% legislature/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=legislature&s=legislature
legislature(X) :- not_implemented(legislature, 1, X).

% member/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=member
member(X) :-
    federal(X),
    government(X),
    polity(X),
    not_implemented(member, 1, X).

% member_state/1 <- http://mathhub.info?a=JLogic/smglol/European-Union-Law&p=mod&m=member-state&s=member%20state
member_state(X) :- not_implemented(member_state, 1, X).

% organization/1 <- http://mathhub.info?a=smglom/orga&p=mod&m=organization&s=organization
organization(X) :- not_implemented(organization, 1, X).

% person/1 <- http://mathhub.info?a=JLogic/smglol/Legal-General-Terms&p=mod&m=person&s=person
person(X) :- not_implemented(person, 1, X).

% policy/1 <- http://mathhub.info?a=smglom/search&p=mod&m=policy&s=policy
policy(X) :- not_implemented(policy, 1, X).

% political_union/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=political-union&s=political%20union
political_union(X) :-
    federal(X),
    government(X),
    polity(X),
    not_implemented(political_union, 1, X).

% polity/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=polity&s=polity
polity(X) :-
    identity(X),
    not_implemented(polity, 1, X).

% set/1 <- http://mathhub.info?a=smglom/sets&p=mod&m=set&s=set
set(X) :- not_implemented(set, 1, X).

% state/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=state&s=state
state(X) :-
    government(X),
    polity(X),
    territory(X),
    not_implemented(state, 1, X).

% supranational_union/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=supranational-union&s=supranational%20union
supranational_union(X) :-
    organization(X),
    political_union(X),
    state(X),
    not_implemented(supranational_union, 1, X).

% territory/1 <- http://mathhub.info?a=JLogic/smglol/Legal-Theory-of-the-State&p=mod&m=territory&s=territory
territory(X) :- not_implemented(territory, 1, X).

% trade_bloc/1 <- http://mathhub.info?a=JLogic/smglol/Public-International-Law&p=mod&m=trade-bloc&s=trade%20bloc
trade_bloc(X) :-
    organization(X),
    state(X),
    not_implemented(trade_bloc, 1, X).

% Every generated predicate starts as an open proof obligation.
not_implemented(belief, 1, _).
not_implemented(court, 1, _).
not_implemented(economic_union, 1, _).
not_implemented(eu, 1, _).
not_implemented(executive, 1, _).
not_implemented(federal, 1, _).
not_implemented(government, 1, _).
not_implemented(identity, 1, _).
not_implemented(judiciary, 1, _).
not_implemented(law, 1, _).
not_implemented(legal, 1, _).
not_implemented(legislature, 1, _).
not_implemented(member, 1, _).
not_implemented(member_state, 1, _).
not_implemented(organization, 1, _).
not_implemented(person, 1, _).
not_implemented(policy, 1, _).
not_implemented(political_union, 1, _).
not_implemented(polity, 1, _).
not_implemented(set, 1, _).
not_implemented(state, 1, _).
not_implemented(supranational_union, 1, _).
not_implemented(territory, 1, _).
not_implemented(trade_bloc, 1, _).

?- eu(X), not_implemented(Node, Arity, X).
