from __future__ import annotations

import hashlib
import html
import re
import unicodedata
import urllib.parse
from collections.abc import Mapping
from html.parser import HTMLParser

from .api import DefinitionFragment
from .graph import PrunedGraph


def symbol_label(uri: str) -> str:
    query = urllib.parse.parse_qs(urllib.parse.urlsplit(uri).query)
    return query.get("s", query.get("m", [uri]))[0]


def prologify(name: str) -> str:
    """Turn a display name into a portable, unquoted Prolog atom."""
    ascii_name = (
        unicodedata.normalize("NFKD", name)
        .encode("ascii", "ignore")
        .decode("ascii")
        .lower()
    )
    atom = re.sub(r"[^a-z0-9]+", "_", ascii_name).strip("_")
    if not atom:
        digest = hashlib.sha256(name.encode("utf-8")).hexdigest()[:8]
        atom = f"node_{digest}"
    elif not atom[0].isalpha():
        atom = "node_" + atom
    return atom


def predicate_names(uris: set[str] | frozenset[str]) -> dict[str, str]:
    """Assign deterministic, unique predicate names to symbol URIs."""
    grouped: dict[str, list[str]] = {}
    for uri in sorted(uris):
        grouped.setdefault(prologify(symbol_label(uri)), []).append(uri)
    result: dict[str, str] = {}
    for base, members in grouped.items():
        for index, uri in enumerate(members, start=1):
            result[uri] = base if index == 1 else f"{base}_{index}"
    return result


class _DefinitionText(HTMLParser):
    _BLOCKS = {
        "br",
        "div",
        "li",
        "math",
        "mrow",
        "p",
        "table",
        "td",
        "tr",
    }

    def __init__(self, symbol_uri: str) -> None:
        super().__init__(convert_charrefs=True)
        self.symbol_uri = symbol_uri
        self.parts: list[str] = []
        self.suppressed_depth = 0
        self.has_placeholder = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if self.suppressed_depth:
            self.suppressed_depth += 1
            return
        attributes = dict(attrs)
        definiendum = attributes.get("data-ftml-definiendum")
        if definiendum and _same_symbol_uri(
            html.unescape(definiendum), self.symbol_uri
        ):
            self.parts.append(" @(X) ")
            self.has_placeholder = True
            self.suppressed_depth = 1
        elif tag in ("script", "style"):
            self.suppressed_depth = 1
        elif tag in self._BLOCKS:
            self.parts.append(" ")

    def handle_startendtag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        if not self.suppressed_depth and tag in self._BLOCKS:
            self.parts.append(" ")

    def handle_endtag(self, tag: str) -> None:
        if self.suppressed_depth:
            self.suppressed_depth -= 1
        elif tag in self._BLOCKS:
            self.parts.append(" ")

    def handle_data(self, data: str) -> None:
        if not self.suppressed_depth:
            self.parts.append(data)


def _same_symbol_uri(left: str, right: str) -> bool:
    """Match semantic URIs while tolerating FLAMS' HTTP/HTTPS normalization."""
    left_parts = urllib.parse.urlsplit(left)
    right_parts = urllib.parse.urlsplit(right)
    return (
        left_parts.netloc.lower(),
        left_parts.path,
        urllib.parse.parse_qsl(left_parts.query, keep_blank_values=True),
    ) == (
        right_parts.netloc.lower(),
        right_parts.path,
        urllib.parse.parse_qsl(right_parts.query, keep_blank_values=True),
    )


def definition_verbalization(fragment_html: str, symbol_uri: str) -> str:
    parser = _DefinitionText(symbol_uri)
    parser.feed(fragment_html)
    text = " ".join("".join(parser.parts).split())
    text = re.sub(r"\s+([,.;:!?)])", r"\1", text)
    text = re.sub(r"([([])\s+", r"\1", text)
    if not parser.has_placeholder:
        text = "@(X): " + text
    return text


def _quoted_atom(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def render_scasp(
    graph: PrunedGraph,
    *,
    definitions: Mapping[str, DefinitionFragment] | None = None,
) -> str:
    names = predicate_names(graph.nodes)
    definitions = definitions or {}
    adjacency: dict[str, list[str]] = {node: [] for node in graph.nodes}
    for source, target in graph.edges:
        adjacency[source].append(target)
    for children in adjacency.values():
        children.sort(key=lambda uri: (names[uri], uri))

    lines = [
        "% Generated by stexcasp.",
        f"% Root: {graph.root}",
        "% Edges point from a concept to the concepts used by its definition.",
        "",
        "#pred not_implemented(Predicate, Arity, X) :: "
        "'@(Predicate)/@(Arity) is not implemented for @(X)'.",
    ]
    for uri in sorted(definitions, key=lambda item: (names[item], item)):
        if uri not in names:
            continue
        wording = definition_verbalization(definitions[uri].html, uri)
        lines.append(f"#pred {names[uri]}(X) :: {_quoted_atom(wording)}.")
    if definitions:
        lines.append("")

    order = [graph.root] + sorted(
        graph.nodes - {graph.root}, key=lambda uri: (names[uri], uri)
    )
    for uri in order:
        predicate = names[uri]
        lines.append(f"% {predicate}/1 <- {uri}")
        goals = [f"{names[child]}(X)" for child in adjacency[uri]]
        goals.append(f"not_implemented({predicate}, 1, X)")
        if len(goals) == 1:
            lines.append(f"{predicate}(X) :- {goals[0]}.")
        else:
            lines.append(f"{predicate}(X) :-")
            for index, goal in enumerate(goals):
                ending = "." if index == len(goals) - 1 else ","
                lines.append(f"    {goal}{ending}")
        lines.append("")

    lines.append("% Every generated predicate starts as an open proof obligation.")
    for uri in sorted(graph.nodes, key=lambda item: (names[item], item)):
        lines.append(f"not_implemented({names[uri]}, 1, _).")
    lines.extend(
        [
            "",
            f"?- {names[graph.root]}(X), not_implemented(Node, Arity, X).",
            "",
        ]
    )
    return "\n".join(lines)
